kotlin.code.style=official

# project
groupId=ru.enzhine
rootProject.name=rtcms4j-notify
versionIdNumber=0.1.0
versionIdStatus=ALPHA

# plugins and dependencies
## sibling
rtcms4jCore=0.1.0-ALPHA
## primary
jvmPluginVersion=2.2.21
springBootVersion=3.5.7
#springCloudVersion=2025.0.0
## secondary
springDependencyManagementVersion=1.1.7
ktlintVersion=13.1.0
springDocVersion=2.2.0
openapiGeneratorVersion=7.16.0
embeddedPostgresBinariesBomVersion=17.5.0
embeddedPostgresVersion=2.1.0
embeddedDatabaseSpringTestVersion=2.6.0
cucumberVersion=7.23.0
jibVersion=3.5.3
